import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Img from 'next/image'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Safe Tutorial: Passkeys',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            padding: '1rem'
          }}
        >
          <a href='https://safe.global'>
            <Img width={95} height={36} alt='safe-logo' src='/safe.svg' />
          </a>
          <div style={{ display: 'flex' }}>
            <a
              href='https://docs.safe.global/home/passkeys-tutorial'
              style={{
                display: 'flex',
                alignItems: 'center',
                marginRight: '1rem'
              }}
            >
              Read tutorial{' '}
              <Img
                width={20}
                height={20}
                alt='link-icon'
                src='/external-link.svg'
                style={{ marginLeft: '0.5rem' }}
              />
            </a>
            <a
              href='https://github.com/5afe/tutorial-passkeys'
              style={{ display: 'flex', alignItems: 'center' }}
            >
              View on GitHub{' '}
              <Img
                width={24}
                height={24}
                alt='github-icon'
                src='/github.svg'
                style={{ marginLeft: '0.5rem' }}
              />
            </a>
          </div>
        </nav>
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: '70vw'
          }}
        >
          <video
            autoPlay
            muted
            playsInline
            loop
            style={{
              width: '90%',
              position: 'absolute',
              top: '20%',
              left: '5%',
              zIndex: -1
            }}
          >
            <source
              src='https://safe.global/videos/Home/safe-2024-hero-vp9.webm'
              type='video/webm'
            />
            <source
              src='https://safe.global/videos/Home/safe-2024-hero-hevc.mov'
              type='video/quicktime; codecs=hvc1'
            />
          </video>
          {children}
        </div>
      </body>
    </html>
  )
}
